### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by maozezhong** [llluo/TensorflowASGD#1]
你好，感谢分享代码。请问你一个问题，感觉在代码中ax_t的更新并没有assing到var上啊，也就是说权值更新一直是按照SGD来的？

**Comment by congjianluo** [comment]
ASGD的权值更新是与SGD一致的，ax的是一个从某个epoch开始保存weight值，并且对于后面的变化有一个衰减的作用。ax的值需要在训练的时候feed进去，用来替换本身的权重值，具体使用可以看一下LeNet里的例子。这个Optim方法，在比较大的数据集上可能效果非常好，在例子里因为是mnist数据集，可能效果一般。但是还是可以看出来它的衰减作用。

**Comment by maozezhong** [comment]
感谢回复，ASGD的原理我知道。
但是你的代码中ax的更新并没用用到var（权重）上啊，也就是每次优化的时候ax是在不断更新的，而var只是按照SGD在更新。
是不是应该修改成下面样子呢？

> if mu != 1:     #从第t0次迭代后后开始累计
>             ax_t = ax.assign(ax + var_t - eta * grad)
>             var_update = var.assign(ax * mu)
>         else:
>             var_update = state_ops.assign(var, var_t - eta * grad)
>             ax_t = ax.assign(var_update)

更新公式是按照这个来的：

avg_fact = 1 / max(t - K, 1)

if avg_fact != 1:
  w_t = avg_fact * (sum(w_prevs) + (w_prev - lr_t * grad(w_prev)))
else:
  w_t = w_prev - lr_t * grad(w_prev)

不知道我的理解是否有问题？望指教～

**Comment by llluo** [comment]
可以参考一下pytorch的版本官方实现的AVSG(https://pytorch.org/docs/master/_modules/torch/optim/asgd.html#ASGD)，可以帮助理解。ax的用来保存多次迭代后有迭代衰减的weight值，ASGD在学习过程中weight值和SGD更新是一致的，不会去影响训练时的weight值。在预测的时候，会用ax的值来替换weight权重值，然后进行计算。

**Comment by congjianluo** [comment]
可以参考一下pytorch的版本官方实现的AVSG[(https://pytorch.org/docs/master/_modules/torch/optim/asgd.html#ASGD)](https://pytorch.org/docs/master/_modules/torch/optim/asgd.html#ASGD)，可以帮助理解。ax的用来保存多次迭代后有迭代衰减的weight值，ASGD在学习过程中weight值和SGD更新是一致的，不会去影响训练时的weight值。在预测的时候，会用ax的值来替换weight权重值，然后进行计算。
